# Configuration for Dockerized Agents
# Uncomment the agents you want to launch. Each agent should be on a new line.

# /home/cortex/agents_tools/agents/roles/coder_agent
# /home/cortex/agents_tools/agents/roles/documentation_agent
# /home/cortex/agents_tools/agents/tools/file_analyzer_agent
# /home/cortex/agents_tools/agents/roles/frontend_developer_agent
# /home/cortex/agents_tools/agents/tools/google_drive_agent
# /home/cortex/agents_tools/agents/roles/historian_agent
/home/cortex/agents_tools/agents/tools/name_generator_agent
/home/cortex/agents_tools/agents/tools/ollama_agent
# /home/cortex/agents_tools/agents/roles/project_office_agent
# /home/cortex/agents_tools/agents/roles/project_shipper_agent
/home/cortex/agents_tools/agents/tools/secret_manager_agent
# /home/cortex/agents_tools/agents/tools/secure_executor_agent
# /home/cortex/agents_tools/agents/roles/solution_architect_agent
# /home/cortex/agents_tools/agents/roles/tester_agent
# /home/cortex/agents_tools/agents/tools/web_surfer_agent
# /home/cortex/agents_tools/agents/roles/workspace_manager_agent
