# Configuration for Dockerized Agents
# Format: AGENT_PATH PORT
# Uncomment the agents you want to launch.

# Core Agents
/home/cortex/agents_tools/agents/core/root_agent 20200

# Roles
# /home/cortex/agents_tools/agents/roles/coder_agent 20201
# /home/cortex/agents_tools/agents/roles/solution_architect_agent 20202
# /home/cortex/agents_tools/agents/roles/tester_agent 20203
# /home/cortex/agents_tools/agents/roles/documentation_agent 20204
# /home/cortex/agents_tools/agents/roles/frontend_developer_agent 20205
# /home/cortex/agents_tools/agents/roles/historian_agent 20206
# /home/cortex/agents_tools/agents/roles/project_office_agent 20207
# /home/cortex/agents_tools/agents/roles/project_shipper_agent 20208
# /home/cortex/agents_tools/agents/roles/workspace_manager_agent 20209

# Tools
# /home/cortex/agents_tools/agents/tools/file_analyzer_agent 20210
# /home/cortex/agents_tools/agents/tools/google_drive_agent 20211
/home/cortex/agents_tools/agents/tools/name_generator_agent 20212
# /home/cortex/agents_tools/agents/tools/ollama_agent 20213
# /home/cortex/agents_tools/agents/tools/secret_manager_agent 20214
# /home/cortex/agents_tools/agents/tools/secure_executor_agent 20215
# /home/cortex/agents_tools/agents/tools/web_surfer_agent 20216
